name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t hanjisu1002/ybigta-teamproject3:amd64 .

      - name: Push Docker image
        run: docker push hanjisu1002/ybigta-teamproject3:amd64

  deploy:
    name: Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull hanjisu1002/ybigta-teamproject3:amd64
            docker stop app || true
            docker rm app || true
            docker run -d \
              --env-file /home/ec2-user/.env \
              --name app \
              -p 8000:8000 \
              hanjisu1002/ybigta-teamproject3:amd64
